### ISSUE TITLE
cassandra-driver sometimes causes RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ivan** [ludiosarchive/terastash#5]
```
# ts add-shoo --rm -c *
2/25.../home/at/terastash/src/index.js:79
                callback(null, {next: () => (
                                      ^

RangeError: Maximum call stack size exceeded
    at Object.next (/home/at/terastash/src/index.js:79:25)
    at condition (/home/at/terastash/node_modules/cassandra-driver/lib/control-connection.js:202:29)
    at /home/at/terastash/node_modules/async/lib/async.js:786:33
    at /home/at/terastash/node_modules/async/lib/async.js:167:37
    at whileIterator (/home/at/terastash/node_modules/cassandra-driver/lib/control-connection.js:208:18)
    at /home/at/terastash/node_modules/async/lib/async.js:787:21
    at /home/at/terastash/node_modules/async/lib/async.js:167:37
    at whileIterator (/home/at/terastash/node_modules/cassandra-driver/lib/control-connection.js:208:18)
    at /home/at/terastash/node_modules/async/lib/async.js:787:21
    at /home/at/terastash/node_modules/async/lib/async.js:167:37
```

**Comment by ivan** [comment]
This project is archived and will not be picked up. Remember to use PostgreSQL, everyone.
