### ISSUE TITLE
cat-range with out-of-bounds range results in AyyError: A.gte(...): !(-25997538469 >= 0)

### ISSUE THREAD

**Issue by ivan** [ludiosarchive/terastash#6]
This needs a better error.

```
FromIA/greader# ts cat-ranges greaderstats_20130624044346.megawarc.json.gz/26000000000-26000000100
AyyError: A.gte(...): !(-25997538469 >= 0)
    at Object.assertSafeNonNegativeInteger (/home/at/terastash/src/utils.js:21:4)
    at streamFile (/home/at/terastash/src/index.js:1390:9)
```

**Comment by ivan** [comment]
This project is archived and will not be picked up.
