### ISSUE TITLE
Aborted HTTP response results in BadData: Authenticated decryption of block N failed

### ISSUE THREAD

**Issue by ivan** [ludiosarchive/terastash#8]
terastash throws `BadData` when an HTTP response is aborted, which is misleading because the data on the server isn't corrupt:

```
# ts find . -t f -0 | xargs -0 ts cat > /dev/null
events.js:141
      throw er; // Unhandled 'error' event
      ^

BadData: Authenticated decryption of block 7,134 failed:
Error: Unsupported state or unable to authenticate data
    at BadData (/home/at/terastash/gcmer.js:106:1)
    at GCMReader._decrypt (/home/at/terastash/gcmer.js:141:13)
    at GCMReader._transform (/home/at/terastash/gcmer.js:179:15)
    at GCMReader.Transform._read (_stream_transform.js:167:10)
    at GCMReader.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at GCMReader.Writable.write (_stream_writable.js:207:11)
    at RightTruncate.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at RightTruncate.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at RightTruncate.Readable.push (_stream_readable.js:110:10)
    at RightTruncate.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:76:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
```

This happens *all* the time when seeking around in mpv on a terastash http server.

**Comment by ivan** [comment]
This project is archived and will not be picked up.
